#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blankscreen = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GuessFailed1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int GuessFailed2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int GuessFailed3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GuessFailed4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GuessFailed5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int GuessFailed6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GuessFailed7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GuessFailed8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002c
			public const int HighScoresListView = 2131165228;
			
			// aapt resource value: 0x7f070010
			public const int btnA = 2131165200;
			
			// aapt resource value: 0x7f070037
			public const int btnAddProfile = 2131165239;
			
			// aapt resource value: 0x7f070011
			public const int btnB = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int btnC = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int btnD = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int btnDeleteEntry = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int btnE = 2131165204;
			
			// aapt resource value: 0x7f070033
			public const int btnEditDB = 2131165235;
			
			// aapt resource value: 0x7f070004
			public const int btnEditDBMainMenu = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int btnF = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int btnG = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int btnH = 2131165207;
			
			// aapt resource value: 0x7f070032
			public const int btnHighScores = 2131165234;
			
			// aapt resource value: 0x7f07002b
			public const int btnHighScoresBack = 2131165227;
			
			// aapt resource value: 0x7f070018
			public const int btnI = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int btnJ = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int btnK = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int btnL = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int btnM = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int btnN = 2131165213;
			
			// aapt resource value: 0x7f07000a
			public const int btnNewGame = 2131165194;
			
			// aapt resource value: 0x7f070031
			public const int btnNewGameScreen = 2131165233;
			
			// aapt resource value: 0x7f07001e
			public const int btnO = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int btnP = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int btnQ = 2131165216;
			
			// aapt resource value: 0x7f070035
			public const int btnQuit = 2131165237;
			
			// aapt resource value: 0x7f070021
			public const int btnR = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int btnS = 2131165218;
			
			// aapt resource value: 0x7f070039
			public const int btnStartGame = 2131165241;
			
			// aapt resource value: 0x7f070023
			public const int btnT = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int btnU = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int btnV = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int btnW = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int btnX = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int btnY = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int btnZ = 2131165225;
			
			// aapt resource value: 0x7f07003b
			public const int btnselectplayerMainMenu = 2131165243;
			
			// aapt resource value: 0x7f07000d
			public const int gamebtnMainMenu = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int imgHangman = 2131165198;
			
			// aapt resource value: 0x7f070030
			public const int imgHangmanTitle = 2131165232;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout3 = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout4 = 2131165189;
			
			// aapt resource value: 0x7f070034
			public const int linearLayout5 = 2131165236;
			
			// aapt resource value: 0x7f07003a
			public const int linearLayout6 = 2131165242;
			
			// aapt resource value: 0x7f070038
			public const int selectPlayerSpinner = 2131165240;
			
			// aapt resource value: 0x7f070009
			public const int spinnereditDB = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int textView1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView3 = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int txtCurrentScore = 2131165195;
			
			// aapt resource value: 0x7f070036
			public const int txtEnterName = 2131165238;
			
			// aapt resource value: 0x7f07000c
			public const int txtGuessesLeft = 2131165196;
			
			// aapt resource value: 0x7f07002a
			public const int txtHighScores = 2131165226;
			
			// aapt resource value: 0x7f07002e
			public const int txtRowName = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int txtRowScore = 2131165231;
			
			// aapt resource value: 0x7f07000f
			public const int txtWordToGuess = 2131165199;
			
			// aapt resource value: 0x7f07002d
			public const int txtrowId = 2131165229;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditDB = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GameScreenLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HighScores = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listview_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectPlayer = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
